### ISSUE TITLE
Antelope response tools not yet functional

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#11]
_From @GoogleCodeExporter on August 1, 2015 21:51_

```
The current functions do load response info. However, completion of the
code will require the deconvolution routines, which are not functioning yet.

```

Original issue reported on code.google.com by `mew...@gmail.com` on 27 Jan 2010 at 11:22

_Copied from original issue: giseislab/gismotools#4_

**Comment by gthompson** [comment]
Carl, is this issue resolved? What needs to be done?

**Comment by carltape** [comment]
I'm not sure what you are referring to. I use the response toolbox
regularly at UAF, but we're not using the latest version.

**Comment by gthompson** [comment]
Mike opened this issue 5 years ago so I was surprised it was still open. I'm satisfied that Carl is able to use it to deconvolve instrument response. Closing the issue.
