### ISSUE TITLE
allow shortcuts in basic math operations (+,-, .*, .^, etc) 

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#28]
_From @CelsoReyes on August 1, 2015 22:36_

Operations run faster when I use `w.data` instead of `get(w,'data')`.
also, checking for identity operator costs very little, yet can provide decent speedup if used.

``` matlab
% example, in waveform/plus
if b == 0
  return
end
a.data = a.data + b;
```

_Copied from original issue: giseislab/gismotools#40_

**Comment by gthompson** [comment]
_From @CelsoReyes on August 13, 2015 14:21_

contraindication is that code gets a little more complex.  Only a little, though.

**Comment by CelsoReyes** [comment]
closing this. I will not implement in TraceData
