### ISSUE TITLE
waveform error on antelope database

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#33]
Problem encountered by Alex Farrell at USF using latest GISMO:

> > snum=datenum(2011,8,21,12,46,47);
> > enum=datenum(2011,8,21,12,47,5);
> > ds=datasource('antelope','/raid/data/antelope/databases/PLUTONS/dbmerged');
> > scnl=scnlobject('*','HHZ','PL') ;  
> > w_raw=waveform(ds,scnl,snum,enum)
> > In an assignment  A(:) = B, the number of elements in A and B must be the same.

Error in load_antelope>buildAntelopeCriteria (line 115)
      critList(N).group(4) = grabCritList('loc', chanTag(N).location);

Error in load_antelope (line 24)
   [criteria, nCriteria] = buildAntelopeCriteria(chanInfo);

Error in load_from_datasource (line 14)
   w = getter(request);

Error in waveform/waveformFromDatasource (line 167)
         w = load_from_datasource(ds, chans, startt, endt, COMBINE_WAVES, usewkaround);

Error in waveform (line 92)
               w = waveformFromDatasource(arg1, as_channeltag(arg2), arg3, arg4);

**Comment by gthompson** [comment]
Latest error message from Alex Farrell:
Now, running the same w_raw = waveform(ds, scnl, eq(earthquake_number).snum, eq(earthquake_number).enum);
With enum as datenum(2011, 8, 21, 12, 47, 5) and snum as datenum(2011, 8, 21, 12, 46, 47)
I get different errors:

Error using load_antelope>crit2expression (line 332)
Not enough input arguments.

Error in load_antelope>getAsExpressions (line 324)
   eachExp = arrayfun(crit2expression, criteria);

Error in load_antelope>get_antelope_traces (line 273)
   allExp = getAsExpressions(criteriaList);

Error in load_antelope (line 48)
      [tr, database, fdb] = get_antelope_traces(...

Error in load_antelope>@(oneDB)load_antelope(request,oneDB) (line 37)
      antelope_load_fn = @(oneDB) load_antelope(request, oneDB);

Error in load_antelope (line 38)
      outputWaveforms = cellfun(antelope_load_fn, database, 'uniformOutput',false); % each cell

**Comment by CelsoReyes** [comment]
I started rewriting to make it easier to read, and may have fixed this bug, too.  Can you try it again with the latest core-work branch?

**Comment by gthompson** [comment]
Will do. I last updated USF Gismo 24 hrs ago.

-----Original Message-----

**Comment by gthompson** [comment]
Looks like it might now be failing on recent changes to scnlobject/ChannelTag:

```
ds = datasource('antelope', '/raid/data/antelope/databases/PLUTONS/dbmerged');
scnl = scnlobject('*', 'HHZ', 'PL');
enum=datenum(2011, 8, 21, 12, 47, 5);
snum=datenum(2011, 8, 21, 12, 46, 47);
w_raw = waveform(ds, scnl, snum, enum);
```

Result:

Error using ChannelTag/set (line 254)
UPGRADE: using set for a ChannelTag. use field notation instead. eg. ch.station = X

Error in waveform/set (line 109)
            all_chantags = set([w.cha_tag],prop_name,val);

Error in load_antelope>traceToWaveform (line 411)
      allw(seg) = set(wBlank, ...

Error in load_antelope>wavesfromtraces (line 81)
      w_scnl.waves = traceToWaveform(tr{traceidx}); %create waveform list

Error in load_antelope>cycleThroughTraces (line 71)
      w(traceidx) = wavesfromtraces(tr, traceidx, COMBINE_WAVEFORMS);

Error in load_antelope (line 31)
         w = cycleThroughTraces(tr, combineWaves);

Error in load_antelope>RecursivelyLoadFromEachDatabase (line 46)
      w = load_antelope(request, database(n));

Error in load_antelope (line 36)
      outputWaveforms = RecursivelyLoadFromEachDatabase(request);

Error in load_from_datasource (line 14)
   w = getter(request);

Error in waveform/waveformFromDatasource (line 167)
         w = load_from_datasource(ds, chans, startt, endt, COMBINE_WAVES, usewkaround);

Error in waveform (line 92)
               w = waveformFromDatasource(arg1, as_channeltag(arg2), arg3, arg4);

Error in alex_test (line 5)
w_raw = waveform(ds, scnl, snum, enum);

**Comment by CelsoReyes** [comment]
That code is designed to point out where upgrades can happen.  I used that
to make sure that correlation was more-or-less completely updated.

I'll change it to a warning, and will at some point include a flag to turn
it on and off.
-C

**Comment by CelsoReyes** [comment]
done

**Comment by gthompson** [comment]
My rewrite of waveform/load_antelope.m solves this.
