### ISSUE TITLE
correlation cookbook no longer works

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#35]
> > c = correlation('DEMO');
> > Error using correlation/check (line 66)
> > CHECK requires a valid method as second parameter.

Error in correlation (line 375)
    elseif ~check(c,'SAMP')

Has "samp" been renamed to something like "samplerate"?

**Comment by CelsoReyes** [comment]
The correlation cookbook doesn't work:

```
>> startup_gismo
  [lots of directories]
>> correlation('cookbook')
Error using correlation (line 241)
Sorry. The correlation cookbook was not found.

>> cookbook(correlation)
Attempt to execute SCRIPT correlation.cookbook as a function:
/Users/celso/Git/GISMO/classes/@correlation/cookbook.m
```

There are a couple problems:
The files within a class directory aren't allowed to be on the matlab file path, not allowing one to call it directly.
the name 'correlation_cookbook' has been changed to cookbook
scripts within a class directory cannot be accessed.

Solution: Turn the cookbook into a function, and if desired, export the data into the workspace using some interactive method.

**Comment by CelsoReyes** [comment]
I think the cookbook is valuable to let them run it, not merely show the web page. The published cookbook should be an accessible online option?

I have it running now.
- Changed cookbook to be a function (method of correlation)
- cookbook returns workspace variables as a struct (optional return parameter)
- removed call to web() in the constructor. -- paths were too confused. we might need to discuss web stuff (I know... I haven't responded to the cookbook document. I'll have to look it over)

**Comment by CelsoReyes** [comment]
btw: check looks for "SAMPLE", while the cookbook asks for "SAMP".  I'm not in favor of using shortened versions of names.

**Comment by gthompson** [comment]
Me neither. Best to be unambiguous.

-----Original Message-----

**Comment by gthompson** [comment]
Yes, I would like cookbooks to serve 3 purposes:

(1) they get published to gismo website, and linked in under wiki/tutorials
(2) users can run them, section by section, for learning
(3) we can drive them by a test function as part of integration testing each day we do major updates

-----Original Message-----

**Comment by gthompson** [comment]
I did not check that correlation cookbook was  a script, or test as I moved. Assumed it was a function promoted to method. My bad. 

-----Original Message-----

**Comment by gthompson** [comment]
Cannot call correlation.cookbook:

```
 correlation.cookbook
```

Undefined variable "correlation" or function "correlation.cookbook".

I think it needs to be a static method. How to do this with the old style of MATLAB OOP?

**Comment by CelsoReyes** [comment]
Directly accessing the cookbook using a correlation object is:
`cookbook(correlation)`
which I just tested, and works on both 2012b and 2015b.  Of course it crashes on one of my systems because parts of correlation require additional toolboxes that aren't installed.
this will also work when correlation is updated. however, you're right it should be static and the proper usage will be
`correlation.cookbook()`
