### ISSUE TITLE
medfilt1 namespace clash

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#36]
When Carl Tape runs this:

fs = 100;
t = 0:1/fs:1;
x = sin(2_pi_t_3)+0.25_sin(2_pi_t*40);
y = medfilt1(x,10);
figure,clf
plot(t,x,t,y),grid on
xlabel 'Time (s)',ylabel Signal
legend('Original','Filtered')
legend boxoff

He gets this error:

Error using hg.root/get
The name 'start' is not an accessible property for an instance of class 'root'.
Error in medfilt1 (line 18)
    s = get(w(n),'start');

Matlab doesn't even "see" the built-in version of medfilt1 -- all it
can see is the GISMO version.

---

**Comment by gthompson** [comment]
medfilt1 is also a GISMO function contributed Dane Ketner that operates on a waveform object

Solution:
- moved GISMO medfilt1 into a package called 'waveform_extensions'. 
- added a test "test_medfilt1.m" to test Carl Tape's script above. It now returns this image:
  ![medfilt1_test](https://cloud.githubusercontent.com/assets/233816/11083301/3fdb1ffe-87da-11e5-87e8-d7a57943866f.png)

**Comment by gthompson** [comment]
An alternative would be to add it directly as a method to waveform, which would then only execute GISMO medfilt1 if the first argument was a waveform object. We have to be careful not to clutter up waveform (and other classes) with rarely used methods, but some are worth promoting. What do you think Celso?

**Comment by CelsoReyes** [comment]
why use the same name at all?  
Anyway, if it's a filter, then it belongs probably as a member of Tracefilter

**Comment by gthompson** [comment]
Good point. Filtmedian? Method or function?

-----Original Message-----

**Comment by gthompson** [comment]
Looking at this is it very closely related to the waveform/smooth method. Just as that wraps the MATLAB smooth function, this wraps the MATLAB medfilt1 function. So I promoted it to a waveform method. Namespace issue is resolved. (Celso has ultimate decision on whether this should be a waveform method though).
