### ISSUE TITLE
trload_css workaround by Carl Tape

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#39]
Carl Tape (with Yun Wang) found that when they make a bulk request for waveform objects, they would either get no waveforms or all the waveforms. I found the same with IceWeb. Mike West documented same issue previously. Desired behaviour is to always return same number of waveform objects as requested, even if some are empty (i.e. a waveform object with metadata but no timeseries data).

Carl & Yun wrote a modified version of waveform which accepts an additional boolean argument. When set to true, it used a function called "load_antelope_workaround". However, Carl reported by email on October 27 that this workaround no longer exists in GISMO. So Carl asked us to use the test script he posted here:

https://code.google.com/p/gismotools/source/detail?r=397

I have put this code into https://github.com/geoscience-community-codes/GISMO/tree/master/tests/trloadcss_test.m. There are 3 sections of code to test. First section is this code:

```
%% example 1 - station COR is a problem
startTime = 7.338198148159491e+05;
endTime = 7.338198194455787e+05;
chan = 'BHZ*';
scnl = scnlobject('*',chan,'','');
ds = datasource('uaf_continuous');
w = waveform(ds,scnl,startTime,endTime); 
whos w
```

I ran this example and result is:

Error using cell/ismember>cellismemberR2012a (line 192)
Input A of class cell and input B of class cell must be cell arrays of
strings, unless one is a string.

Error in cell/ismember (line 56)
    [varargout{1:max(1,nargout)}] = cellismemberR2012a(A,B);

Error in load_antelope>get_antelope_traces (line 272)
   criteriaList = criteriaList(ismember(critFields, dbFields));

Error in load_antelope (line 48)
      [tr, database, fdb] = get_antelope_traces(...

Error in load_antelope>@(oneDB)load_antelope(request,oneDB) (line 37)
      antelope_load_fn = @(oneDB) load_antelope(request, oneDB);

Error in load_antelope (line 38)
      outputWaveforms = cellfun(antelope_load_fn, database,
      'uniformOutput',false); % each cell

Error in load_from_datasource (line 14)
   w = getter(request);

Error in waveform/waveformFromDatasource (line 167)
         w = load_from_datasource(ds, chans, startt, endt,
         COMBINE_WAVES, usewkaround);

Error in waveform (line 92)
               w = waveformFromDatasource(arg1, as_channeltag(arg2),
               arg3, arg4);

**Comment by gthompson** [comment]
I ran Carl's other examples too. Problem does not seem currently to be with trload_css. Instead it seems that recent modifications to waveform mean that waveform will not load data from Antelope in any circumstance. About to post a minimal Antelope example as a new issue.

**Comment by gthompson** [comment]
Following Celso's fix to issue 39 I turned trloadcss_test.m. This first test partially works - with old GISMO Carl found it returned 0 waveform objects. With new GISMO it returns 1. But 2 were requested. The second should be an empty waveform object because there are no data for COR.

```
startTime = datenum(2009,2,15,19,33,20);
endTime = datenum(2009,2,15,19,40,0);
ds = datasource('uaf_continuous');
chan='BHZ*';
scnl = scnlobject({'COLA';'COR'},chan,'','');
w = waveform(ds,scnl,startTime,endTime)
```

Warning: couldn't open the waveform file for COR:BHZ_00 at  2/15/2009 (046)  0:00:00.023

trload_css: No matching data were found
Warning: Waveform:load_antelope:trload_css failed 

> In @waveform/private/load_antelope>get_antelope_traces/cleanUpFail at 313
>   In @waveform/private/load_antelope>get_antelope_traces at 289
>   In @waveform/private/load_antelope at 29
>   In @waveform/private/load_antelope>RecursivelyLoadFromEachDatabase at 46
>   In @waveform/private/load_antelope at 36
>   In @waveform/private/load_from_datasource at 14
>   In waveform.waveform>waveformFromDatasource at 167
>   In waveform.waveform at 92 
>     database: 114
>        table: 35
>        field: -501
>       record: -501
> sta=~/COR/ && chan=~/BHZ.*/
> 1234726400 1234726800
>  starttimes: 15-Feb-2009 19:33:20
> endtimes: 15-Feb-2009 19:40:00
> trload_css(mydb, starttimes, endtimes))
> Warning: failed to interpret database pointer

??? Error using dbclose

Usage: DBCLOSE ( DBPTR )

w =
 ChannelTag: -.COLA..BHZ       [network.station.location.channel]
      start: 2009-02-15 19:33:20.048
             duration(00:06:40.000)
       data: 8000 samples
       freq: 20.0000    Hz
      units: nm / sec
    history: [1 items], last modification: 12-Nov-2015 15:11:48
    With misc fields...
    \* CALIB: 1.1094
    \* CALIBRATION_APPLIED: YES

**Comment by gthompson** [comment]
However, this example fails:

```
    startTime = '2000/07/31 22:44:38';
    endTime = '2000/07/31 23:59:38';
    scnl = scnlobject('*','BHZ_01','','');
    db = '/home/admin/databases/BEAAR/wf/beaar';
    ds = datasource('antelope',db);
    w = waveform(ds,scnl,startTime,endTime)
```

Warning: some failure reading and interpreting the data for DH1:BHZ_01 at  7/31/2000 (213) 21:43:58.069

Warning: Waveform:load_antelope:trload_css failed 

> In @waveform/private/load_antelope>get_antelope_traces/cleanUpFail at 313
>   In @waveform/private/load_antelope>get_antelope_traces at 289
>   In @waveform/private/load_antelope at 29
>   In @waveform/private/load_antelope>RecursivelyLoadFromEachDatabase at 46
>   In @waveform/private/load_antelope at 36
>   In @waveform/private/load_from_datasource at 14
>   In waveform.waveform>waveformFromDatasource at 167
>   In waveform.waveform at 92 
>     '/home/admin/databases/BEAAR/wf/beaar'
> sta=~/.*/ && chan=~/BHZ_01/
> 965083478 965087978
>  starttimes: 31-Jul-2000 22:44:37
> endtimes: 31-Jul-2000 23:59:37
> trload_css(mydb, starttimes, endtimes))
> Warning: failed to interpret database pointer

??? Error using dbclose

Usage: DBCLOSE ( DBPTR )

w =
  no waveform

**Comment by gthompson** [comment]
This test fails also:

```
startTime = datenum(2011,11,16,16,29,0);
endTime = startTime + 1/100;
sta = '*';
chan = 'HHZ*';
scnl = scnlobject(sta,chan,'','');
ds = datasource('uaf_continuous');
w = waveform(ds,scnl,startTime,endTime)
```

Warning: some failure reading and interpreting the data for AKT:HHZ at 11/16/2011 (320) 15:44:27.706

Warning: Waveform:load_antelope:trload_css failed 

> In @waveform/private/load_antelope>get_antelope_traces/cleanUpFail at 313
>   In @waveform/private/load_antelope>get_antelope_traces at 289
>   In @waveform/private/load_antelope at 29
>   In @waveform/private/load_antelope>RecursivelyLoadFromEachDatabase at 46
>   In @waveform/private/load_antelope at 36
>   In @waveform/private/load_from_datasource at 14
>   In waveform.waveform>waveformFromDatasource at 167
>   In waveform.waveform at 92 
>     '/aerun/sum/db/archive/archive_2011/archive_2011_11_16'
> sta=~/._/ && chan=~/HHZ._/
> 1321460940 1321461804
>  starttimes: 16-Nov-2011 16:29:00
> endtimes: 16-Nov-2011 16:43:24
> trload_css(mydb, starttimes, endtimes))
> Warning: failed to interpret database pointer

??? Error using dbclose

Usage: DBCLOSE ( DBPTR )

w =
  no waveform

**Comment by carltape** [comment]
% trload_css error example (station COR)
startTime = 7.338198148159491e+05;
endTime = 7.338198194455787e+05;
chan = 'BHZ_';
datestr(startTime)
scnl = scnlobject('_',chan,'','');
ds = datasource('uaf_continuous');
% OLD VERSION: returns nothing; NEW VERSION: returns 108 waveforms
w = waveform(ds,scnl,startTime,endTime); whos w
% OLD VERSION: returns 196 waveforms
w = waveform(ds,scnl,startTime,endTime,true); whos w

Hey Glenn,
I tried this in the latest version. There is no longer any exit error, and 108 waveforms are returned. But in the old version (GISMO_DEV at UAF), it returns 196 waveforms. The difference is between BHZ and BHZ\* (which gives BHZ_00 among others). Seems like we are close to solving this test case.
Thanks,
Carl

**Comment by gthompson** [comment]
I wrote a new, simpler version of waveform/private/load_antelope.m in May/June 2016, and this seems to have resolved these issues as intended.
