### ISSUE TITLE
waveform not loading any data from Antelope

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#40]
Here is a minimal example which should load 1 hour of data from the EHZ channel at station RSO on Redoubt on 2009/03/20:

```
scnl = scnlobject('RSO','EHZ')
ds = datasource('uaf_continuous')
w=waveform(ds,scnl,datenum(2009,3,20),datenum(2009,3,20,1,0,0))
```

Result:

Error using cell/ismember>cellismemberR2012a (line 192)
Input A of class cell and input B of class cell must be cell arrays of
strings, unless one is a string.

Error in cell/ismember (line 56)
    [varargout{1:max(1,nargout)}] = cellismemberR2012a(A,B);

Error in load_antelope>get_antelope_traces (line 272)
   criteriaList = criteriaList(ismember(critFields, dbFields));

Error in load_antelope (line 48)
      [tr, database, fdb] = get_antelope_traces(...

Error in load_antelope>@(oneDB)load_antelope(request,oneDB) (line 37)
      antelope_load_fn = @(oneDB) load_antelope(request, oneDB);

Error in load_antelope (line 38)
      outputWaveforms = cellfun(antelope_load_fn, database,
      'uniformOutput',false); % each cell

Error in load_from_datasource (line 14)
   w = getter(request);

Error in waveform/waveformFromDatasource (line 167)
         w = load_from_datasource(ds, chans, startt, endt,
         COMBINE_WAVES, usewkaround);

Error in waveform (line 92)
               w = waveformFromDatasource(arg1, as_channeltag(arg2),
               arg3, arg4);

**Comment by gthompson** [comment]
Note that the MiniSEED file does exist. This can be checked with the "listMiniseedFiles" function in the antelope package of core GISMO:

> > flist = antelope.listMiniseedFiles(ds,scnl,datenum(2009,3,20),datenum(2009,3,20,1,0,0))

flist = 

```
filepath: '/aerun/sum/db/archive/archive_2009/2009/079/RSO.EHZ.2009:079:00:00:00'
  exists: 2
```

(Tried reading this directly with the miniseed class, but that class needs additional work.)

**Comment by gthompson** [comment]
Added the function

tests/waveform_antelope_test

and a demo Antelope database at tests/test_data/demodb

So now when running

```
gismodir = fileparts(which('startup_GISMO'));
demodbpath = fullfile(gismodir, 'tests', 'test_data', 'demodb');
scnl = scnlobject('RSO','EHZ')
ctag = ChannelTag('.RSO..EHZ')
ds = datasource('antelope',demodbpath)
flist=antelope.listMiniseedFiles(ds,ctag,datenum(2009,3,20),datenum(2009,3,20,1,0,0))
if sum(flist.exists)>0
    w=waveform(ds,ctag,datenum(2009,3,20),datenum(2009,3,20,1,0,0))
else
    disp('No waveform files found')
end
```

Result is:
        scnl =

```
       station: RSO
       channel: EHZ
       network: 
      location: 

    ctag = 

    ChannelTag with network.station.location.channel:
       network: ''
       station: 'RSO'
      location: ''
       channel: 'EHZ'

    ds =

          type: ANTELOPE
      location: /home/glenn/src/GISMO/tests/test_data/demodb

    ddfullfile = 

        '/home/glenn/src/GISMO/tests/test_data/miniseed/RSO.EHZ.2009:079:00:00:00'
        '/home/glenn/src/GISMO/tests/test_data/miniseed/RSO.EHZ.2009:079:00:00:00'
        '/home/glenn/src/GISMO/tests/test_data/miniseed/RSO.EHZ.2009:079:00:00:00'


    flist = 

        filepath: '/home/glenn/src/GISMO/tests/test_data/miniseed/RSO.EHZ.2009:079:00:00:00'
          exists: 2


    dbFields = 

        'sta'
        'chan'
        'time'
        'wfid'
        'chanid'
        'jdate'
        'endtime'
        'nsamp'
        'samprate'
        'calib'
        'calper'
        'instype'
        'segtype'
        'datatype'
        'clip'
        'dir'
        'dfile'
        'foff'
        'commid'
        'lddate'


    critFields = 

        'sta'    []    'chan'


    critFields = 

        'sta'    'chan'


    criteriaList = 

    1x2 struct array with fields:

        field
        relationship
        value


    ans =

    sta


    ans =

         []


    ans =

    =~


    ans =

         []


    ans =

    RSO


    ans =

         []

    Error using load_antelope>crit2expression (line 336)
    Not enough input arguments.

    Error in load_antelope>getAsExpressions (line 328)
       eachExp = arrayfun(crit2expression, criteria);


    Error in load_antelope>get_antelope_traces (line 277)
       allExp = getAsExpressions(criteriaList);


    Error in load_antelope (line 48)
          [tr, database, fdb] = get_antelope_traces(...


    Error in load_antelope>@(oneDB)load_antelope(request,oneDB) (line 37)
          antelope_load_fn = @(oneDB) load_antelope(request, oneDB);


    Error in load_antelope (line 38)
          outputWaveforms = cellfun(antelope_load_fn, database, 'uniformOutput',false); % each cell


    Error in load_from_datasource (line 14)
       w = getter(request);

    Error in waveform/waveformFromDatasource (line 167)
             w = load_from_datasource(ds, chans, startt, endt, COMBINE_WAVES, usewkaround);


    Error in waveform (line 92)
                   w = waveformFromDatasource(arg1, as_channeltag(arg2), arg3, arg4);


    >>
```

**Comment by CelsoReyes** [comment]
I just tried it while logging in to badger -- and it worked. (?)

```
Your version of Antelope is /opt/antelope/5.4
GISMO added OK
swarm usgs.gov added OK
... using 64-bit libraries
>> scnl = scnlobject('RSO','EHZ')
scnl =
   station: RSO
   channel: EHZ
   network: --
  location: --
>> ds = datasource('uaf_continuous')
ds =
      type: ANTELOPE
  location: /aerun/sum/db/archive/archive_[YEAR]/archive_[YEAR]_[MONTH]_[DAY]
>> w=waveform(ds,scnl,datenum(2009,3,20),datenum(2009,3,20,1,0,0))
alk_verify_lcache_file: Error opening license cache file /tmp/.lcache_1.1/fl: No such file or directory
Unable to verify license cache file /tmp/.lcache_1.1/fl
Attempt to recreate /tmp/.lcache_1.1/fl successful
w =
   station:    RSO       network: --
   channel:    EHZ      location: --
     start: 2009-03-20 00:00:00.001
            duration(00:59:59.999)
      data: 359998 samples
      freq:    99.9995 Hz
     units: nm / sec
   history: [4 items], last modification: 11-Nov-2015 21:37:36
    With misc fields...
    * CALIBRATION_APPLIED: YES
    * CALIB: 1.237
>> 
```

**Comment by CelsoReyes** [comment]
BTW this was directly after cloning our git. No other changes were made.
here's the start of my session
```
[celso@badger ~]$ cd Git
[celso@badger Git]$ git clone https://github.com/geoscience-community-codes/GISMO.git GISMO
Initialized empty Git repository in /home/celso/Git/GISMO/.git/
remote: Counting objects: 6803, done.
remote: Total 6803 (delta 0), reused 0 (delta 0), pack-reused 6803
Receiving objects: 100% (6803/6803), 99.19 MiB | 6.47 MiB/s, done.
Resolving deltas: 100% (4433/4433), done.
[celso@badger Git]$ matlab

                                                                                     < M A T L A B (R) >
                                                                           Copyright 1984-2014 The MathWorks, Inc.
                                                                             R2014a (8.3.0.532) 64-bit (glnxa64)
                                                                                      February 11, 2014
```

**Comment by CelsoReyes** [comment]
OH. crud. Using the old one. Sorry!

**Comment by CelsoReyes** [comment]
OK. I fixed it. There were a few issues.

When I compared criteria to database fields, I had thought that `ismember` could handle a many:many relationship. I was wrong.
New logic has been moved to another subroutine, `keepCriteriaThatMatchDatabaseFields`, which checks for both empty criteria and examines the fields 1-by-1.

For some reason the waveforms aren't being combined yet.

Oh, and I also fixed conversions from Waveform to SeismicTrace. Both will work now:

``` matlab
scnl = scnlobject('RSO','EHZ');
ds = datasource('uaf_continuous');
w=waveform(ds,scnl,datenum(2009,3,20),datenum(2009,3,20,1,0,0))
% or
T=SeismicTrace.retrieve(ds,scnl,datenum(2009,3,20),datenum(2009,3,20,1,0,0))
```

**Comment by gthompson** [comment]
Awesome - thanks! Big help. Hopefully combine is easier to figure out.

Up at 4am here in Alaska trying to debug why the darn fancy timer thing at ellens rental doesn't come on as temperatures head to -26f. No way to bypass...built into home circuitry....

-----Original Message-----

**Comment by gthompson** [comment]
Retested with 
    runtests('waveform_antelope_test')

Result - old and new methods both pass:

> > runtests('waveform_antelope_test')
> > Running waveform_antelope_test

w =

[3x1] waveform object with fields:
     ChannelTag
     start
     freq
     data
     units
     history
   with common fields...
    'CALIB'
    'CALIBRATION_APPLIED'

.
T = 

[3x1] SeismicTrace containing:
net.sta.lo.cha  firstsample       nsamples  samprate     duration
-.RSO..EHZ  2009-03-20 00:00:00.001     84337     100.000   00:14:3.370
-.RSO..EHZ  2009-03-20 00:14:03.380    101000     100.000   00:16:50.000
-.RSO..EHZ  2009-03-20 00:30:53.391    174660      99.999   00:29:6.610
.
Done waveform_antelope_test

---

ans = 

  1x2 TestResult array with properties:

```
Name
Passed
Failed
Incomplete
Duration
```

Totals:
   2 Passed, 0 Failed, 0 Incomplete.
   0.10222 seconds testing time.


As you predicted however, waveform/SeismicTrace objects do not get combined. But:

```
w = combine(w)
```

or 

```
T = T.combine()
```

does work.
