### ISSUE TITLE
Problems installing Gismo

### ISSUE THREAD

**Issue by rcabdia** [geoscience-community-codes/GISMO#52]
Hello my name is Roberto,

I would like to install correctly GISMO  but I have a problema,
1. I copy in my directory c:/Sismica/Gismo-master and unzip the program here (following the instructions image 1).
2. I add the two lines indicated Image 2
3. I Run startup but Matlab give an error continuosly image 3, Pehaps because core and depreciated are Split??

So I need signal processing toolbox to run GISMO?
How can I get a free versión of signal processing toolbox ?
![matlabgismo](https://cloud.githubusercontent.com/assets/22215772/18548497/4b599f1e-7b49-11e6-86d7-91dce1f26640.png)
![matlabgismo](https://cloud.githubusercontent.com/assets/22215772/18548546/9aad2be4-7b49-11e6-842b-0b47950c0134.png)
![matlabgismo2](https://cloud.githubusercontent.com/assets/22215772/18548547/9ab15af2-7b49-11e6-9c19-c5d8846edb72.png)
![matlabgismo3](https://cloud.githubusercontent.com/assets/22215772/18548545/9aaa663e-7b49-11e6-81ca-ccf0329584d2.png)

![matlabgismo2](https://cloud.githubusercontent.com/assets/22215772/18548498/4b5b50c0-7b49-11e6-9351-2ca0b4efeee9.png)
![matlabgismo3](https://cloud.githubusercontent.com/assets/22215772/18548499/4b5f90f4-7b49-11e6-990e-dbe23dde61ec.png)

thnak you so much for your answer

**Comment by gthompson** [comment]
Hi Roberto,

The problem is that you put those two lines into startup_GISMO.m

They are supposed to go in startup.m, as the instructions say.

By putting them in startup_GISMO you are telling startup_GISMO to call
itself, which calls itself, ... an infinite loop.
- Glenn
