### ISSUE TITLE
Working with a signal

### ISSUE THREAD

**Issue by rcabdia** [geoscience-community-codes/GISMO#53]
Hello,

Please, I would like to ask something about import sac files.

Now I ve run GISMO properlu an I loaded a sac file (this sac file come from a miniseed, and using a dataless and the program rdseed I transformed to sac)
1. The amplitud of this signal (Y-AXIS) it must be in m/s not in counts, right?? because i've used a dataless.
2. I ve download signal processing toolbox, but it is impossible to open the variable w.
3. How can I quit the response of the instrument?? I Have also ples&zeros file to do it but I don't know do it in GISMO
   t
   he link to the sac file;

https://www.dropbox.com/s/162u5o4lkvp0q0e/2014.070.00.00.00.2200.WM.UCM..HHZ.D.SAC?dl=0

images;

![matlabgismo4](https://cloud.githubusercontent.com/assets/22215772/18582202/37222294-7c04-11e6-9b97-9a470412a056.png)
![matlabgismo5](https://cloud.githubusercontent.com/assets/22215772/18582204/3723fca4-7c04-11e6-8a2e-234ae1c99586.png)
![matlabgismo6](https://cloud.githubusercontent.com/assets/22215772/18582203/3723d832-7c04-11e6-9a81-a8534f9d10dc.png)

Thank you for everything

**Comment by gthompson** [comment]
Hi,

Please pose questions like this to the user group mailing list directly. Do not open them as issues because I am not notified of them. I just find this now, months later, and the link has expired anyway.

Thanks

Glenn
