### ISSUE TITLE
Make a class for units

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#6]
_From @CelsoReyes on August 1, 2015 22:44_

which would be used by waveform & friends, 
So it can handle integrate and diff, for example.

_Copied from original issue: giseislab/gismotools#47_

**Comment by CelsoReyes** [comment]
A class exists, but it is in its infancy, and hasn't been implemented yet. 
measurementunit

**Comment by gthompson** [comment]
Not sure this is needed, and Celso has left the building. This is definitely a low priority development idea, rather than a burning issue.
